---
- name: Create a instances
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws3
    instance_type: t2.micro
    security_group: homework
    image: ami-04505e74c0741db8d
    region: us-east-1
  tasks:
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: Open ports 22, 8080
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch build
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         group: "{{ security_group }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-02de6ea80a0f4f962
         assign_public_ip: yes
    - name: Install maven
      apt:
          name: maven
          state: latest
    - name: Install git
      apt:
          name: git
          state: latest
    - name: Clone a repo to directory
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/1/maven/
    - name: build war
      shell: mvn package -B -f /tmp/1/maven
    - name: Simple PUT operation
      aws_s3:
        bucket: severov.boxfuse
        object: /my/desired/boxfuse/hello-1.0.war
        src: /tmp/1/maven/target/hello-1.0.war
        mode: put
    - name: Launch prod
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         group: "{{ security_group }}"
         region: "{{ region }}"
         vpc_subnet_id: subnet-02de6ea80a0f4f962
         assign_public_ip: yes
#    - name: install JDK 11
#      apt:
#          name: openjdk-11-jdk
#          state: present
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: default-jdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat10
      unarchive:
        src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat- 10.0.4.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: [ --strip-components=1 ]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      copy:
        src: /etc/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
    - name: s3 get operation
      aws_s3:
        bucket: severov.boxfuse
        object: /my/desired/boxfuse/hello-1.0.war
        dest: /opt/tomcat10/webapps/hello-1.0.war
        mode: get


