---
- name: Create a instances
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws3
    instance_type: t2.micro
    security_group: homework
    image: ami-04505e74c0741db8d
    region: us-east-1
  tasks:
    - name: Create a security group
      ec2_group:
        name: "{{ security_group }}"
        description: Open ports 22, 8080
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch build
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-02de6ea80a0f4f962
         assign_public_ip: yes
    - name: Install maven
      apt:
          name: maven
          state: latest
    - name: Install git
      apt:
          name: git
          state: latest
    - name: Clone a repo to directory
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/1/maven/
    - name: build war
      shell: mvn package -B -f /tmp/1/maven
    - name: Simple PUT operation
      aws_s3:
        bucket: severov.boxfuse
        object: /my/desired/boxfuse/hello-1.0.war
        src: /tmp/1/maven/target/hello-1.0.war
        mode: put
    - name: Launch prod
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-02de6ea80a0f4f962
         assign_public_ip: yes
#    - name: install JDK 11
#      apt:
#          name: openjdk-11-jdk
#          state: present
    - name: install tomcat9
      apt:
          name: tomcat9
          state: latest
    - name: s3 get operation
      aws_s3:
        bucket: severov.boxfuse
        object: /my/desired/boxfuse/hello-1.0.war
        dest: /var/lib/webapps/hello-1.0.war
        mode: get


