---
- name: Create a instances
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws2
    instance_type: m3.micro
    security_group: my_securitygroup
    image: ami-092cce4a19b438926
    region: eu-north-1
    group: ['build', 'prod']
    count: 2
  tasks:
    - name: Launch build
      ec2:
         key_name: "{{ keypair }}"
         group: build
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes
    - name: Launch prod
      ec2:
         key_name: "{{ keypair }}"
         group: prod
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes


