- name: build war
  tasks:
    - name: Install maven
      apt:
        name: maven
        state: latest
    - name: Install git
      apt:
        name: git
        state: latest
    - name: Clone a repo to directory
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/1/maven/
    - name: build war
      command: mvn package -B -f /tmp/mvn/1
    - name: Simple PUT operation
      amazon.aws.aws_s3:
        bucket: boxfuse
        object: /my/desired/boxfuse/
        src: /tmp/1/maven/target/hello-1.0.war
        mode: put
- name: public app
  tasks:
    - name: install tomcat
      apt:
        name: tomcat9
- name: Simple GET operation
                amazon.aws.aws_s3:
 #                 AWS_ACCESS_KEY_ID: AKIAXJWLXA3F6DBE2KMQ
  #                AWS_ACCESS_KEY: ZIsSwwE4cITIR8jfyE4yYdYMGxGB/tl56M8qphQB
   #               bucket: boxfuse
    #              object: /my/desired/key.txt
     #             dest: /usr/local/myfile.txt
      #            mode: get

                  - name: install tomcat9
                    shell: apt update && apt install -y tomcat9
                  - name: s3 get operation
                    aws_s3:
                      bucket: severov.boxfuse
                      object: /my/desired/boxfuse/hello-1.0.war
                      dest: /var/lib/tomcat9/webapps/hello-1.0.war
                      mode: get