version: "3"
services:
  tomcat:
    build: tom_msql
    volumes:
      - mydata:/opt/tomcat/webapps/
    ports:
      - "8084:8080"
      - "3306:3306"
    environment:
          MYSQL_DATABASE: myDb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
    depends_on:
      - "maven"
  maven:
    build: mvn
    volumes:
      - mydata:/tmp/mvn/1/target/

volumes:
    mydata: