version: "3"
services:
  tomcat:
    image: tomcat:9.0.58-jre8-openjdk-slim-bullseye
    volumes:
      - mydata:/usr/local/tomcat/webapps/
      - ./Config.properties:/usr/local/tomcat/ROOT/Config.properties
    ports:
      - "8084:8080"
    depends_on:
      - "maven"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
          MYSQL_DATABASE: dd
          MYSQL_USER: acp4pogynvaeidfj
          MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
          MYSQL_ROOT_PASSWORD: test
    depends_on:
      - "maven"
  maven:
    build: mvn
    volumes:
      - mydata:/tmp/mvn/1/target/
  redis:
    image: redis:latest
volumes:
    mydata:
