version: "3"
services:
  tomcat:
    build: tom_msql
    volumes:
      - mydata:/opt/tomcat/webapps/
    ports:
      - "8084:8080"
  mysql:
    build: mysql
    ports:
      - "3306:3306"
    environment:
          MYSQL_DATABASE: dd
          MYSQL_USER: acp4pogynvaeidfj
          MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
          MYSQL_ROOT_PASSWORD: test
    depends_on:
      - "maven"
  maven:
    build: mvn
    volumes:
      - ./content:/tmp/mvn/1/WebContent/
      - mydata:/tmp/mvn/1/target/
mysql://mysql:3306
volumes:
    mydata: