version: "3"
services:
  tomcat:
    build: tom_msql
    volumes:
      - mydata:/opt/tomcat/webapps/
    ports:
      - "8084:8080"
    depends_on:
      - "maven"
      - "mysql"
  maven:
    build: mvn
    volumes:
      - mydata:/tmp/mvn/1/target/
  mysql:
    build: mysql
    ports:
      - "8514:33060"
    environment:
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_ROOT_PASSWORD: test

volumes:
    mydata: