version: "3"
services:
  tomcat:
    build: Tomcat
    volumes:
      - mydata:/usr/local/tomcat/webapps/
    ports:
      - "8080:8080"
    depends_on:
      - "maven"
  maven:
    build: mvn
    volumes:
      - mydata:/tmp/mvn/1/target/

volumes:
    mydata: